const HomeProduct = [
  {
    id: 1,
    Name: "Tv",
    price: 99,
    images: "images/p1.webp",
    cat: "tv",
    type: "New",
  },
  {
    id: 2,
    Name: "Laptop",
    price: 96,
    images: "images/p2.webp",
    cat: "laptop",
    type: "Featured",
  },
  {
    id: 3,
    Name: "Watch",
    price: 66,
    images: "images/p3.webp",
    cat: "watch",
    type: "Top",
  },
  {
    id: 4,
    Name: "Speaker",
    price: 88,
    images: "images/p4.webp",
    cat: "speaker",
    type: "Featured",
  },
  {
    id: 5,
    Name: "Electronics",
    price: 42,
    images: "images/p5.webp",
    cat: "electronics",
    type: "New",
  },
  {
    id: 6,
    Name: "Phone",
    price: 82,
    images: "images/p6.webp",
    cat: "phone",
    type: "Featured",
  },
  {
    id: 7,
    Name: "Headphone",
    price: 45,
    images: "images/p7.webp",
    cat: "headphone",
    type: "New",
  },
  {
    id: 8,
    Name: "Speaker",
    price: 36,
    images: "images/p8.webp",
    cat: "speaker",
    type: "Top",
  },
  {
    id: 9,
    Name: "Laptop",
    price: 102,
    images: "images/p9.jpg",
    cat: "laptop",
    type: "Featured",
  },
  {
    id: 10,
    Name: "Headphone",
    price: 68,
    images: "images/p10.jpg",
    cat: "headphone",
    type: "New",
  },
  {
    id: 11,
    Name: "Tv",
    price: 102,
    images: "images/p1.webp",
    cat: "tv",
    type: "Featured",
  },
  {
    id: 11,
    Name: "Laptop",
    price: 105,
    images: "images/p9.jpg",
    cat: "laptop",
    type: "Top",
  },
];

export default HomeProduct;
